// <auto-generated />
using BackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(MaMaDbContext))]
    partial class MaMaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.Models.Hairdresser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("SalonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Hairdressers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Lat = 55.710031999999998,
                            Lng = 9.5347290000000005,
                            SalonName = "Hairværk",
                            Website = "https://hairvaerkvejle.dk/"
                        },
                        new
                        {
                            ID = 2,
                            Lat = 55.612772999999997,
                            Lng = 9.5668050000000004,
                            SalonName = "Salon No. 24",
                            Website = "https://salonno24.dk/"
                        },
                        new
                        {
                            ID = 3,
                            Lat = 55.711891000000001,
                            Lng = 9.5365300000000008,
                            SalonName = "Frisør PARK Styling Vejle",
                            Website = "https://parkstyling.dk/pages/salon/vejle"
                        },
                        new
                        {
                            ID = 4,
                            Lat = 55.710152000000001,
                            Lng = 9.5352700000000006,
                            SalonName = "City Frisørerne",
                            Website = "https://parkstyling.dk/pages/salon/vejle-city"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
